### PR TITLE
added ui process code - WORKING HTML

### PR DESCRIPTION
**Pull request by laurenalto**

### CODE REVIEW

**Review by laurenalto — COMMENTED** [review]
use this one

**Comment by AG2048** [comment]
um there's merge conflicts... idk how to resolve this

**Comment by AG2048** [comment]
seems like the whole files are in conflict, i'm worried i might accidentally delete the wrong file...

**Comment by kwangzera** [comment]
these html files are the most recent, we can do a force merge

**Comment by kwangzera** [comment]
Ok i deleted the old files so the new ones can be added in

**Pull request merged**
